server:
  port: 8415

spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems-admin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 12345678
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      idle-timeout: 3000
      max-lifetime: 50000

  # 请求超时时间
  mvc:
    async:
      request-timeout: 5000ms

  redis:
    database: 1
    host: localhost
    port: 6379

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

